@baseUrl = https://localhost:7001


################################################## AnswerQuestions
POST {{baseUrl}}/AnswerQuestions/DeserializeJsonString/abc
#####
POST {{baseUrl}}/AnswerQuestions/UpdateCriticism/abc
#####
