@baseUrl = https://localhost:44333


################################################## AnswerQuestions
POST {{baseUrl}}/AnswerQuestions/DeserializeJsonString/abc
#####
POST {{baseUrl}}/AnswerQuestions/UpdateCriticism/abc
#####
